sudo: required
language: cpp
matrix:
    include:
        # GCC 5
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
              packages:
                - g++-5
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
          env:
             - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        # GCC 6
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
              packages:
                - g++-6
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        # GCC 7
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
              packages:
                - g++-7
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

script:
    - mkdir -p build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=${CXX} ..
    - make
    - ./tests

notifications:
    email: false
