sudo: required
language: cpp
matrix:
    include:
        # GCC 5
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
                - sourceline: 'ppa:nschloe/eigen-backports'
              packages:
                - g++-5
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
                # Coverage report
                - lcov
          env:
             - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
        # GCC 6
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
                - sourceline: 'ppa:nschloe/eigen-backports'
              packages:
                - g++-6
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
                # Coverage report
                - lcov
          env:
            - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
        # GCC 7
        - os: linux
          addons:
            apt:
              sources:
                - ubuntu-toolchain-r-test
                - sourceline: 'ppa:tsvetko.tsvetkov/trusty-backports'
                - sourceline: 'ppa:nschloe/eigen-backports'
              packages:
                - g++-7
                - libeigen3-dev
                # GSL
                - libgsl2
                - libgsl-dev
                # Coverage report
                - lcov
          env:
            - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"

before_install:
    - eval $MATRIX_EVAL
script:
    - chmod +x build.sh
    - ./set_travis_build_options.sh
    - ./build.sh debug test
    - ./build/tests

after_success:
    # Creating report
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --capture --output-file coverage.info # capture coverage info
  - lcov --remove coverage.info '/usr/*' --output-file coverage.info # filter out system
  - lcov --list coverage.info #debug info
  # Uploading report to CodeCov
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

notifications:
    email: false
